spring.application.name=foodzone

#mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodies

#aws configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=eu-north-1
aws.s3.bucketname=foodies-bank

jwt.secret.key=${JWT_SECRET}
# jwt secret key: yourverysecuresecretkeyateast256bitsongAjhfvxDvhdgwkbbbfjvgdrjvdj07t73vdubjwdjvuy8yebfjgvbudsbfBJBJVHgjbjvgjbb7vhfr5fv


#razorpay configuration
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}

//qazxswedcvfrtgbnhyujm